[package]
name = "ev3_proto_client"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.14.2"
prost = "0.13"
ev3_proto = { path = "../ev3_proto" }
tokio = { version = "1.0", features = ["macros", "rt-multi-thread", "sync"] }
