[package]
name = "ev3_proto"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.14.2"
prost = "0.14.1"
tonic-prost = "*"

[build-dependencies]
tonic-build = "0.14.2"
tonic-prost-build = "0.14.2"
