[package]
name = "ev3_pb"
version = "0.1.0"
edition.workspace = true

[dependencies]
tonic = "0.12"
prost = "0.13"
pb = { path = "../pb" }
tokio = { version = "1.0", features = ["macros", "rt-multi-thread", "sync"] }